const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');const hpEl=document.getElementById('health'),ammoEl=document.getElementById('ammo'),msgEl=document.getElementById('message');
const map=['111111111111','100000000001','100010000001','100010011101','100000010001','101100010001','100000000001','100011110001','100000000001','100001000001','100000000001','111111111111'];
const keys={};let W,H;const p={x:2.5,y:2.5,a:0,hp:100,ammo:30,reserve:90,shoot:0,reloading:false};const enemies=[{x:9.5,y:2.5,hp:100,alive:true},{x:9.5,y:8.5,hp:100,alive:true},{x:3.5,y:9.5,hp:100,alive:true}];let locked=false,paused=true,last=performance.now(),flash=0,hitFlash=0;
function resize(){W=canvas.width=innerWidth*devicePixelRatio;H=canvas.height=innerHeight*devicePixelRatio;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.imageSmoothingEnabled=false}addEventListener('resize',resize);resize();
addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyR')reload();if(e.code==='Escape'){paused=!paused;msgEl.textContent=paused?'CLICK TO PLAY':''}});addEventListener('keyup',e=>keys[e.code]=false);
canvas.addEventListener('click',()=>{canvas.requestPointerLock?.();paused=false;msgEl.textContent=''});document.addEventListener('pointerlockchange',()=>{locked=document.pointerLockElement===canvas;if(!locked&&!paused){paused=true;msgEl.textContent='CLICK TO PLAY'}});document.addEventListener('mousemove',e=>{if(locked&&!paused)p.a+=e.movementX*.0025});
function cell(x,y){const xi=Math.floor(x),yi=Math.floor(y);return map[yi]?.[xi]!=='0'}function move(dx,dy){if(!cell(p.x+dx,p.y))p.x+=dx;if(!cell(p.x,p.y+dy))p.y+=dy}
function reload(){if(p.reloading||p.ammo>=30||p.reserve<=0)return;p.reloading=true;ammoEl.classList.add('reloading');setTimeout(()=>{let n=Math.min(30-p.ammo,p.reserve);p.ammo+=n;p.reserve-=n;p.reloading=false;ammoEl.classList.remove('reloading')},1200)}
function fire(){if(paused||p.reloading||p.shoot>0)return;if(p.ammo<=0){reload();return}p.ammo--;p.shoot=.11;flash=.06;let best=null,bd=99;for(const e of enemies){if(!e.alive)continue;let dx=e.x-p.x,dy=e.y-p.y,d=Math.hypot(dx,dy),ang=Math.atan2(dy,dx);let da=Math.atan2(Math.sin(ang-p.a),Math.cos(ang-p.a));if(Math.abs(da)<.055&&d<bd&&visible(e.x,e.y)){best=e;bd=d}}if(best){best.hp-=34;if(best.hp<=0)best.alive=false}}
canvas.addEventListener('mousedown',e=>{if(e.button===0){canvas.requestPointerLock?.();fire()}});
function visible(x,y){const d=Math.hypot(x-p.x,y-p.y),n=Math.ceil(d*10);for(let i=1;i<n;i++){let t=i/n;if(cell(p.x+(x-p.x)*t,p.y+(y-p.y)*t))return false}return true}
function update(dt){if(paused)return;p.shoot=Math.max(0,p.shoot-dt);flash=Math.max(0,flash-dt);hitFlash=Math.max(0,hitFlash-dt);let sp=keys.ShiftLeft||keys.ShiftRight?3.8:2.5,dx=0,dy=0;if(keys.KeyW){dx+=Math.cos(p.a)*sp*dt;dy+=Math.sin(p.a)*sp*dt}if(keys.KeyS){dx-=Math.cos(p.a)*sp*dt;dy-=Math.sin(p.a)*sp*dt}if(keys.KeyA){dx+=Math.cos(p.a-Math.PI/2)*sp*dt;dy+=Math.sin(p.a-Math.PI/2)*sp*dt}if(keys.KeyD){dx+=Math.cos(p.a+Math.PI/2)*sp*dt;dy+=Math.sin(p.a+Math.PI/2)*sp*dt}move(dx,dy);if(keys.Space){}if(keys.Mouse0)fire();for(const e of enemies){if(!e.alive)continue;let d=Math.hypot(e.x-p.x,e.y-p.y);if(d<7&&visible(e.x,e.y)){let a=Math.atan2(p.y-e.y,p.x-e.x);let ex=Math.cos(a)*dt*.35,ey=Math.sin(a)*dt*.35;if(d>1.8&&!cell(e.x+ex,e.y))e.x+=ex;if(d>1.8&&!cell(e.x,e.y+ey))e.y+=ey;if(d<8&&Math.random()<dt*.18){p.hp=Math.max(0,p.hp-7);hitFlash=.12}}}if(p.hp<=0){paused=true;msgEl.textContent='YOU DIED — CLICK TO RESTART';setTimeout(()=>{if(p.hp<=0){p.hp=100;p.x=2.5;p.y=2.5;p.ammo=30;p.reserve=90;enemies.forEach(e=>{e.alive=true;e.hp=100})}},700)}}
function cast(a){let s=Math.sin(a),c=Math.cos(a),d=0;while(d<20){d+=.025;if(cell(p.x+c*d,p.y+s*d))break}return d}
function render(){ctx.fillStyle='#9bb7c9';ctx.fillRect(0,0,W,H/2);ctx.fillStyle='#303238';ctx.fillRect(0,H/2,W,H/2);const fov=Math.PI/3,rays=Math.floor(W/3);for(let i=0;i<rays;i++){let a=p.a-fov/2+fov*i/rays,d=cast(a)*Math.cos(a-p.a),h=Math.min(H*2,H/d*.75),x=i*3;let shade=Math.max(20,170-d*12);ctx.fillStyle=`rgb(${shade},${shade},${shade})`;ctx.fillRect(x,H/2-h/2,4,h)}const visibleEnemies=enemies.filter(e=>e.alive&&visible(e.x,e.y)).map(e=>{let dx=e.x-p.x,dy=e.y-p.y,d=Math.hypot(dx,dy),a=Math.atan2(dy,dx),da=Math.atan2(Math.sin(a-p.a),Math.cos(a-p.a));return{e,d,da}}).filter(o=>Math.abs(o.da)<fov/2+.1).sort((a,b)=>b.d-a.d);for(const o of visibleEnemies){let size=Math.min(H*1.3,H/o.d*.65),sx=W/2+(o.da/fov)*W;ctx.fillStyle='#d33';ctx.fillRect(sx-size*.22,H/2-size*.5,size*.44,size);ctx.fillStyle='#f2b6a0';ctx.beginPath();ctx.arc(sx,H/2-size*.58,size*.18,0,Math.PI*2);ctx.fill()}if(flash){ctx.fillStyle='#ffd166';ctx.beginPath();ctx.moveTo(W/2,H*.56);ctx.lineTo(W/2-30,H*.7);ctx.lineTo(W/2,H*.65);ctx.lineTo(W/2+30,H*.7);ctx.fill()}if(hitFlash){ctx.fillStyle='rgba(255,0,0,.18)';ctx.fillRect(0,0,W,H)}hpEl.textContent=`HP ${Math.ceil(p.hp)}`;ammoEl.textContent=`${p.ammo} / ${p.reserve}`;ammoEl.classList.toggle('low',p.ammo<=5)}
function loop(t){const dt=Math.min(.05,(t-last)/1000);last=t;update(dt);render();requestAnimationFrame(loop)}requestAnimationFrame(loop);
